export const contributors = [
  {
    fullName: 'Alice Johnson',
    avatarUrl: '/avatars/1.png',
    email: 'alice@example.com',
    githubLink: 'https://github.com/alicejohnson',
    totalScore: 1550,
    contributions: [
      {
        title: 'Implement User Authentication',
        project: 'RankForge Backend',
        score: 300,
      },
      {
        title: 'Add Leaderboard Frontend Component',
        project: 'RankForge Frontend',
        score: 250,
      },
      {
        title: 'Documentation for API Endpoints',
        project: 'RankForge Docs',
        score: 200,
      },
    ],
  },
  {
    fullName: 'Bob Williams',
    avatarUrl: '/avatars/2.png',
    email: 'bob@example.com',
    githubLink: 'https://github.com/bobwilliamsdev',
    totalScore: 1420,
    contributions: [
      {
        title: 'Develop Admin Scoring Interface',
        project: 'RankForge Frontend',
        score: 280,
      },
      {
        title: 'Database Schema Design',
        project: 'RankForge Backend',
        score: 220,
      },
      {
        title: 'Fix Bug in Contribution Submission Form',
        project: 'RankForge Frontend',
        score: 150,
      },
    ],
  },
  {
    fullName: 'Charlie Brown',
    avatarUrl: '/avatars/3.png',
    email: 'charlie@example.com',
    githubLink: 'https://github.com/charlieb',
    totalScore: 1380,
    contributions: [
      {
        title: 'Refactor Authentication Flow',
        project: 'RankForge Backend',
        score: 270,
      },
      {
        title: 'Create Reusable UI Components',
        project: 'RankForge Frontend',
        score: 210,
      },
      {
        title: 'Write Unit Tests for Scoring Logic',
        project: 'RankForge Backend',
        score: 180,
      },
    ],
  },
  {
    fullName: 'Diana Miller',
    avatarUrl: '/avatars/4.png',
    email: 'diana@example.com',
    githubLink: 'https://github.com/dianam',
    totalScore: 1210,
    contributions: [
      {
        title: 'Design User Dashboard Layout',
        project: 'RankForge Frontend',
        score: 240,
      },
      {
        title: 'Add Input Validation to Forms',
        project: 'RankForge Backend',
        score: 190,
      },
      {
        title: 'Update README with Contribution Guidelines',
        project: 'RankForge Docs',
        score: 120,
      },
    ],
  },
  {
    fullName: 'Ethan Davis',
    avatarUrl: '/avatars/5.png',
    email: 'ethan@example.com',
    githubLink: 'https://github.com/ethand',
    totalScore: 1195,
    contributions: [
      {
        title: 'Set up CI/CD Pipeline',
        project: 'DevOps',
        score: 260,
      },
      {
        title: 'Optimize Database Queries',
        project: 'RankForge Backend',
        score: 205,
      },
      {
        title: 'Add Basic Styling to Public Pages',
        project: 'RankForge Frontend',
        score: 110,
      },
    ],
  },
  {
    fullName: 'Fiona Green',
    avatarUrl: '/avatars/6.png',
    email: 'fiona@example.com',
    githubLink: 'https://github.com/fionag',
    totalScore: 1150,
    contributions: [
      {
        title: 'Implement Role-Based Access Control',
        project: 'RankForge Backend',
        score: 290,
      },
      {
        title: 'Create Admin User Interface',
        project: 'RankForge Frontend',
        score: 230,
      },
      {
        title: 'Review and Score 15 Contributions',
        project: 'Admin Activity',
        score: 150,
      },
    ],
  },
  {
    fullName: 'George White',
    avatarUrl: '/avatars/7.png',
    email: 'george@example.com',
    githubLink: 'https://github.com/georgew',
    totalScore: 1080,
    contributions: [
      {
        title: 'Set up Production Environment',
        project: 'DevOps',
        score: 250,
      },
      {
        title: 'Write API Documentation',
        project: 'RankForge Docs',
        score: 190,
      },
      {
        title: 'Add User Profile Endpoint',
        project: 'RankForge Backend',
        score: 160,
      },
    ],
  },
  {
    fullName: 'Hannah Black',
    avatarUrl: '/avatars/8.png',
    email: 'hannah@example.com',
    githubLink: 'https://github.com/hannahb',
    totalScore: 1020,
    contributions: [
      {
        title: 'Design Public Leaderboard Page',
        project: 'RankForge Frontend',
        score: 220,
      },
      {
        title: 'Create Contribution Data Model',
        project: 'RankForge Backend',
        score: 180,
      },
      {
        title: 'Add Basic Styling to Forms',
        project: 'RankForge Frontend',
        score: 100,
      },
    ],
  },
  {
    fullName: 'Isaac Blue',
    avatarUrl: '/avatars/9.png',
    email: 'isaac@example.com',
    githubLink: 'https://github.com/isaacb',
    totalScore: 980,
    contributions: [
      {
        title: 'Implement JWT Authentication',
        project: 'RankForge Backend',
        score: 270,
      },
      {
        title: 'Add User Registration Endpoint',
        project: 'RankForge Backend',
        score: 190,
      },
      {
        title: 'Write Developer Setup Guide',
        project: 'RankForge Docs',
        score: 130,
      },
    ],
  },
  {
    fullName: 'Jasmine Red',
    avatarUrl: '/avatars/10.png',
    email: 'jasmine@example.com',
    githubLink: 'https://github.com/jasminer',
    totalScore: 910,
    contributions: [
      {
        title: 'Create Contributor Dashboard Layout',
        project: 'RankForge Frontend',
        score: 200,
      },
      {
        title: 'Add Contribution Submission Endpoint',
        project: 'RankForge Backend',
        score: 170,
      },
      {
        title: 'Design Homepage Intro Section',
        project: 'RankForge Frontend',
        score: 100,
      },
    ],
  },
]
export const leaderboard = [
  {
    rank: 1,
    fullName: 'Alice Johnson',
    totalScore: 1550,
    contributions: 120,
    imageUrl: '/avatars/1.png',
  },
  {
    rank: 2,
    fullName: 'Bob Williams',
    totalScore: 1420,
    contributions: 110,
    imageUrl: '/avatars/2.png',
  },
  {
    rank: 3,
    fullName: 'Charlie Brown',
    totalScore: 1380,
    contributions: 105,
    imageUrl: '/avatars/3.png',
  },
  {
    rank: 4,
    fullName: 'Diana Miller',
    totalScore: 1210,
    contributions: 98,
    imageUrl: '/avatars/4.png',
  },
  {
    rank: 5,
    fullName: 'Ethan Davis',
    totalScore: 1195,
    contributions: 95,
    imageUrl: '/avatars/5.png',
  },
  {
    rank: 6,
    fullName: 'Fiona Green',
    totalScore: 1150,
    contributions: 90,
    imageUrl: '/avatars/6.png',
  },
  {
    rank: 7,
    fullName: 'George White',
    totalScore: 1080,
    contributions: 85,
    imageUrl: '/avatars/7.png',
  },
  {
    rank: 8,
    fullName: 'Hannah Black',
    totalScore: 1020,
    contributions: 80,
    imageUrl: '/avatars/8.png',
  },
  {
    rank: 9,
    fullName: 'Isaac Blue',
    totalScore: 980,
    contributions: 75,
    imageUrl: '/avatars/9.png',
  },
  {
    rank: 10,
    fullName: 'Jasmine Red',
    totalScore: 910,
    contributions: 70,
    imageUrl: '/avatars/10.png',
  },
  {
    rank: 11,
    fullName: 'Kevin Yellow',
    totalScore: 880,
    contributions: 65,
    imageUrl: '/avatars/11.png',
  },
  {
    rank: 12,
    fullName: 'Laura Purple',
    totalScore: 850,
    contributions: 60,
    imageUrl: '/avatars/12.png',
  },
  {
    rank: 13,
    fullName: 'Michael Orange',
    totalScore: 790,
    contributions: 55,
    imageUrl: '/avatars/13.png',
  },
  {
    rank: 14,
    fullName: 'Nora Pink',
    totalScore: 760,
    contributions: 50,
    imageUrl: '/avatars/14.png',
  },
  {
    rank: 15,
    fullName: 'Oliver Grey',
    totalScore: 720,
    contributions: 45,
    imageUrl: '/avatars/15.png',
  },
  {
    rank: 16,
    fullName: 'Paula Cyan',
    totalScore: 680,
    contributions: 40,
    imageUrl: '/avatars/1.png',
  },
  {
    rank: 17,
    fullName: 'Quentin Magenta',
    totalScore: 650,
    contributions: 35,
    imageUrl: '/avatars/2.png',
  },
  {
    rank: 18,
    fullName: 'Rachel Teal',
    totalScore: 610,
    contributions: 30,
    imageUrl: '/avatars/18.png',
  },
  {
    rank: 19,
    fullName: 'Sam Olive',
    totalScore: 580,
    contributions: 25,
    imageUrl: '/avatars/19.png',
  },
  {
    rank: 20,
    fullName: 'Tina Lime',
    totalScore: 550,
    contributions: 20,
    imageUrl: '/avatars/20.png',
  },
]
